### ISSUE TITLE
License under dual MIT/Apache-2.0

### ISSUE THREAD

**Issue by est31** [rust-lang/fmt-rfcs#175]
This is an issue to license the rust-lang/fmt-rfcs repo under dual Apache2 OR MIT licensing terms. Currently there is no license file in this git repository, I have made a draft PR for Apache2 OR MIT licensing terms: https://github.com/rust-lang/fmt-rfcs/pull/174

You are receiving this notification because you have contributed to this repo.

## Checkoff

To agree to the licensing terms, please comment in this thread with:

> I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

Thank you! :heart: 

- [x] @nrc
- [x] @joshtriplett 
- [x] @johnthagen 
- [x] @calebcartwright 
- [x] @solson 
- [x] @BenjaminBrienen 
- [x] @pushkine 
- [x] @cherryblossom000 
- [x] @pickfire 
- [x] @daniel-vainsencher 
- [x] @camelid 
- [x] @ahl 
- [x] @CYBAI 
- [x] @Rufflewind 
- [x] @kraai 
- [x] @strega-nil / ubsan

For general comments, given the number of people subscribed to this issue, I recommend keeping discussion to the PR in #174 or the [zulip topic](https://rust-lang.zulipchat.com/#narrow/stream/346005-t-style/topic/License.20of.20the.20RFCs). Thanks!

**Comment by cherryblossom000** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by Rufflewind** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by CYBAI** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by BenjaminBrienen** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by kraai** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by johnthagen** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by nrc** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by daniel-vainsencher** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by pickfire** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by calebcartwright** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by ahl** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by solson** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by pushkine** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by strega-nil** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by camelid** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by est31** [comment]
I'm closing this as resolved, as all authors have given their consent.

Thanks again! :heart: 

[Archived link](http://web.archive.org/web/20221218060746/https://github.com/rust-lang/fmt-rfcs/issues/175)
